#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftA,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lifter,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     spinner,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    drawBridge,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabOne,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    grabTwo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servoTurret,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//** Team 7890: Space Lions
//** Horace Mann School, Bronx, NY
//** Version: 3/8/15
//** Tournament Iteration: NJ State Championship (NJIT)
//** Authors: Nick Keirstead, Jacob Hoglund, Joshua Gruenstein

//Goal of Program:
	//- Drive down ramp (20 pts)
	//- Latch onto and haul 60 cm rolling goal to our parking zone (20 pts)
	//--> ideal total = 40 pts


//Sensing Used:
		//- Custom Ultrasonic Sensor, connected to HiTechnic SuperPro Prototype Board
		//- Motor encoders
		//- HiTechnic Gyroscope


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "helperFunctions.h"

void initializeRobot()
{
	bridgeClosed();
	grabbersUp();
	wait1Msec(500);
}

void downRamp () {
	driveDistance(-20,DOWN_RAMP_DIST);
	grabbersDown();
}

void grabSixty () {
	driveDistance(-20,20); //figure out dist
	wait1Msec(200);
	lifterUpThirty();
	lifterUpThirty();
	wait1Msec(500);
	driveDistance(-15,15);
	wait1Msec(2000);
	bridgeOpen();
	wait1Msec(1000);
	grabbersDown();
	wait1Msec(1000);
}

void haulSixty () { //to parking zone
	int angle = 45;
	pivot(1,20,angle);
	wait1Msec(50);
	driveDistance(20,20);
	wait1Msec(100);
 	pivot(0,20,20);
  wait1Msec(100);
 	driveDistance(20,120);
}

void returnFromSixty () { //to parking zone
	driveDistance(30,45);
}

void grabNinety () {
	driveDistance(DRIVE_PACE,20);
	wait1Msec(100);
	pivot(0,DRIVE_PACE/4,169);
	wait1Msec(50);
	driveDistance(DRIVE_PACE,-115);
	wait1Msec(500);
	grabbersDown();
	wait1Msec(500);
}

void haulNinety () {
	driveDistance(100,130);
}

void cascadeEffect () {
	downRamp();
	haulSixty();

	//grabSixty();
	//haulSixty();
	//returnFromSixty();
	//grabSixty();
	//haulSixty();
	//wait1Msec(100);
	//grabSixty();
	//wait1Msec(100);
	//haulSixty();
	//wait1Msec(100);
	//grabNinety();
	//wait1Msec(100);
	//haulNinety();
}

////**************
//// TASKS SECTION

task main() {
	initializeRobot();
	//setupMenu();
	//bDisplayDiagnostics = false; //clear brick of normal diagnostics text
	//startTask(runMenu);
	//wait1Msec(5000); //switch out for wait for start in competition
	waitForStart(); // Wait for the beginning of autonomous phase.

	//stopTask(runMenu); //stop running selector menu
	//eraseDisplay(); //clear brick
	//bDisplayDiagnostics = true;//display normal diagnostics again

	cascadeEffect();//run autonomous with inputted delay
	//driveDistance(15,12);
}



////******************
//// NOTES SECTION

// Wheel diameter = 4in
// Wheel circumference = 4 * pi = 12.57
// distance traveled = wheel rotations * circumference
// 									 = (degrees turned/360) * circumference
// 									 = (encoder ticks/360) * circumference
// --> encoder ticks = (360/circumference) * distance
// --> encoder ticks = (360/12.57) * distance
// --> encoder ticks = (360/12.57) * 1 inch
// --> encoder ticks/1inch = 29
