#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftA,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lifter,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     spinner,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    drawbridge,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabOne,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    grabTwo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servoTurret,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//** Team 7890: Space Lions
//** Horace Mann School, Bronx, NY
//** Version: 3/8/15
//** Tournament Iteration: NJ State Championship (NJIT)
//** Authors: Nick Keirstead, Jacob Hoglund, Joshua Gruenstein

//Goal of Program:
	//- Determine position of center structure with sonar
	//- Knock out kickstand (30 pts)
	//--> ideal total = 30 pts

//Sensing Used:
		//- Custom Sonar Rangefinder connected to HiTechnic Superpro Protoboard
		//- HiTechnic Gyroscope
		//- Motor Encoders

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "helperFunctions.h"



void initializeRobot()
{
	servo[servoTurret] = 128; //point custom rangefinder forward
	grabbersMidway();
	bridgeClosed();
}

void knockStand (int position) {
	switch (position) {
		case 1:
			driveUntilCloserThan(15,90);
			wait1Msec(100);
			pivot(1,50,90);
			break;
		case 2:
			servo[servoTurret] = 75;
			wait1Msec(600);
			driveUntilCloserThan(15,116);
			wait1Msec(100);
			driveDistance(-15,1);
			wait1Msec(100);
			pivot(1,18,31);
			wait1Msec(100);
			driveDistance(50,15);
			wait1Msec(100);
			pivot(1,15,15);
			wait1Msec(100);
			break;
		case 3:
			driveUntilCloserThan(15,200);
			wait1Msec(100);
			pivot(1,15,35);
			wait1Msec(100);
			driveDistance(15,20);
			wait1Msec(100);
			pivot(0,15,28);
			wait1Msec(100);
			driveDistance(100,25);
	}
}


task main()
{
		initializeRobot();
		waitForStart();
		int position = findOrientation();
		//nxtDisplayTextLine(2, "Position: %d", position);
		//wait1Msec(1000);
		knockStand(position);
}
