#pragma config(Sensor, S4,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   HiTechnic Experimenter's Kit for the SuperPro

Experiment - 7 Magnetic Switch Sensor

This program measures reads the status of the magnetic sensor and outputs the status.

*/

#include "prodrive.h"



task main() {
  int inputdata;

  // Set B0 for output
  HTSPBsetupIO(HTSPB, 0x1);

  while(true) {
    // Read a 10bit wide analogue value from A0
    inputdata = 0;
		for (int i=0; i<10; i++) {
  		inputdata += HTSPBreadADC(HTSPB, 0, 10);
  		wait1Msec(20);
		}
		inputdata /= 10;
		nxtDisplayTextLine(1, "A0: %d", inputdata);
    // If A0 is less than 50% of the max value
    // turn off the LED, otherwise switch it on
  }
}
