#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C2_1,     rightA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftA,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     leftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    ballDump,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    grabOne,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    grabTwo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servoTurret,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//** Team 7890: Space Lions
//** Horace Mann School, Bronx, NY
//** Version: 1/18/15
//** Tournament Iteration:
//** Authors: Nick Keirstead, Jacob Hoglund, Joshua Gruenstein

#define BALL_DUMP_UP 110
#define BALL_DUMP_DOWN 255
#define GRABBERS_UP 5
#define GRABBERS_DOWN 220

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
int threshold = 10;
bool forwards = true;
bool lifterUp = false;
bool slowDriveMode = false;

void initializeRobot() {
	servo[grabOne] = servo[grabTwo] = 0;//reset tube-grabbers to up position
	servoChangeRate[ballDump] = 10;
	return;
}

////****************************
////  DRIVE FUNCTIONS SECTION
void setMotor (tMotor arbMotor, int power) {
	motor[arbMotor] = power;
}

void powerSide (int dir, int power) {
	if (dir == 0) {
		setMotor(leftA,power);
		setMotor(leftB,power);
	}
	else if (dir == 1) {
		setMotor(rightA,power);
		setMotor(rightB,power);
	}
}

void drive (int leftPow, int rightPow) {
	powerSide(0,leftPow);
	powerSide(1,rightPow);
}

void straightDrive (int power) {
	drive(power, power);
}

void halt () {
	straightDrive(0);
}

task raiseLifter () {
	//
	lifterUp = true;
}

task lowerLifter () {
	//
	lifterUp = false;
}

task main() {
  initializeRobot();
  //waitForStart();   // wait for start of teleop phase
  while (true) {
		if (forwards) {
  		if (abs(joystick.joy1_y1) > threshold) motor[leftA] = motor[leftB] = joystick.joy1_y1;
			else motor[leftA] = motor[leftB] = 0;
			if (abs(joystick.joy1_y2) > threshold) motor[rightA] = motor[rightB] = joystick.joy1_y2;
			else motor[rightA] = motor[rightB] = 0;
		}
		else {
			if (abs(joystick.joy1_y1) > threshold) motor[leftA] = motor[leftB] = -joystick.joy1_y2;
			else motor[leftA] = motor[leftB] = 0;
			if (abs(joystick.joy1_y2) > threshold) motor[rightA] = motor[rightB] = -joystick.joy1_y1;
			else powerSide(1,0);
		}

		//rolling goal grabber servos
		if (joy1Btn(3)) servo[grabOne] = servo[grabTwo] = GRABBERS_DOWN;
		if (joy1Btn(1)) servo[grabOne] = servo[grabTwo] = GRABBERS_UP;

		if (joy2Btn(6)) servo[ballDump] = BALL_DUMP_UP;
		if (joy2Btn(5)) servo[ballDump] = BALL_DUMP_DOWN;

		//scissor lift
		if (abs(joystick.joy2_y1) > threshold) motor[liftLeft] = motor[liftRight] = joystick.joy2_y1 * 0.5;
		else motor[liftLeft] = motor[liftRight] = 0;

		//toggle motor direction
		if (joy1Btn(4)) forwards = true;
		if (joy1Btn(2)) forwards = false;

		if (joystick.joy1_TopHat == 4) {
			slowDriveMode = true;
		}
		if (joystick.joy1_TopHat == 0) {
			slowDriveMode = false;
		}
		if (slowDriveMode == true) {
			motor[leftA] *= 0.5;
			motor[leftB] *= 0.5;
			motor[rightA] *= 0.5;
			motor[rightB] *= 0.5;
		}


  }
}
